version: '3'

services:
  user-service:
    build: ./
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=your_jwt_secret_here
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb
      - auth-service
    networks:
      - backend

  auth-service:
    build: ../auth-service
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=your_jwt_secret_here
    networks:
      - backend

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge
